### ISSUE TITLE
hackhttp不支持python3

### ISSUE THREAD

**Issue by wivd** [BugScanTeam/hackhttp#10]
hackhttp库在python2下用这个很方便，目前很多库都已经支持python3，很多生产系统也在用python3进行开发。能否考虑一下hackhttp这个库，也支持一下python3，这样python3下也可以继续使用这个库了。

**Comment by Medicean** [comment]
@wivd 感谢支持，短期内暂不会支持 Py3，后期可能会考虑支持 Py3
