### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by zer0yu** [BugScanTeam/hackhttp#11]
当我hh.http(url)时会出现400错误，但是我用requests库就没有这种问题

比如我的url值为：

http://localhost/[PATH]/index.php?option=com_coupon&view=coupons&catid=7+AND+(SELECT+1+FROM+(SELECT+COUNT(*),CONCAT((SELECT(SELECT+CONCAT(CAST(CONCAT(username,char(58),password)+AS+CHAR),0x7e))+FROM+wl6xp_users+LIMIT+0,1),FLOOR(RAND(0)*2))x+FROM+INFORMATION_SCHEMA.TABLES+GROUP+BY+x)a)

的时候。

**Comment by Medicean** [comment]
@zer0yu 我在本地测了一下，没复现成功。你试着把 payload 部分用 `urllib.quote`编码一下呢？

<img width="1091" alt="hh" src="https://cloud.githubusercontent.com/assets/6082020/23580554/fd3f06da-013e-11e7-93b5-79ba2e655d1e.png">

**Comment by zer0yu** [comment]
好的，谢谢

2017-03-05 1:01 GMT+08:00 undefined <notifications@github.com>:
