### ISSUE TITLE
ironpython  加载hackhttp 报错

### ISSUE THREAD

**Issue by coider** [BugScanTeam/hackhttp#7]
C:\Users\wine\Desktop>ipy test2.py
  File "C:\Users\wine\Desktop\hackhttp__init__.py", line ?

```
^
```

SyntaxError: unknown encoding type

**Comment by coider** [comment]
未处理 Microsoft.Scripting.SyntaxErrorException
  Message=unknown encoding type
  Source=IronPython
  Column=0
  ErrorCode=0
  Line=0
  SourcePath=C:\Users\wine\Desktop\hackhttp__init__.py
  StackTrace:
       在 IronPython.Runtime.ThrowingErrorSink.Add(SourceUnit sourceUnit, String message, SourceSpan span, Int32 errorCode, Severity severity)
       在 IronPython.Compiler.Parser.CreateParserWorker(CompilerContext context, PythonOptions options, Boolean verbatim)
       在 IronPython.Runtime.PythonContext.ParseAndBindAst(CompilerContext context)
       在 IronPython.Runtime.PythonContext.CompilePythonCode(SourceUnit sourceUnit, CompilerOptions options, ErrorSink errorSink)
       在 IronPython.Runtime.PythonContext.CompileModule(String fileName, String moduleName, SourceUnit sourceCode, ModuleOptions options, ScriptCode& scriptCode)
       在 IronPython.Runtime.PythonContext.CompileModule(String fileName, String moduleName, SourceUnit sourceCode, ModuleOptions options)
       在 IronPython.Runtime.Importer.LoadFromSourceUnit(CodeContext context, SourceUnit sourceCode, String name, String path)
       在 IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
       在 IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
       在 IronPython.Runtime.Importer.ImportTopAbsolute(CodeContext context, String name)
       在 IronPython.Runtime.Importer.ImportModule(CodeContext context, Object globals, String modName, Boolean bottom, Int32 level)
       在 IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
       在 IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
       在 Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
       在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
       在 Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
       在 IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
       在 IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
       在 Microsoft.Scripting.SourceUnit.Execute(Scope scope)
       在 WindowsFormsApplication1.Form1.button3_Click(Object sender, EventArgs e) 位置 F:\vssources\WindowsFormsApplication1\WindowsFormsApplication1\Form1.cs:行号 254
       在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       在 System.Windows.Forms.Control.WndProc(Message& m)
       在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
       在 System.Windows.Forms.Button.WndProc(Message& m)
       在 System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       在 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       在 WindowsFormsApplication1.Program.Main() 位置 F:\vssources\WindowsFormsApplication1\WindowsFormsApplication1\Program.cs:行号 18
       在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       在 System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by Medicean** [comment]
这个应该是你的 `test2.py` 里面的文件缺少了编码声明造成的。
